import Foundation

struct Asset {
    var name: String
    var path: String
}

struct ComponentAsset {
    var sourceName: String
    var constantName: String
}

func writeStandardError(_ message: String) {
    FileHandle.standardError.write(Data(message.utf8))
}

let arguments = Array(CommandLine.arguments.dropFirst())
guard let outputFlag = arguments.firstIndex(of: "--output"),
      outputFlag + 1 < arguments.count else {
    writeStandardError("Usage: InksteadWriterAssets --output path name=file...\n")
    exit(2)
}

let outputPath = arguments[outputFlag + 1]
let specs = arguments.dropFirst(outputFlag + 2)

let assets: [Asset] = specs.map { spec in
    guard let separator = spec.firstIndex(of: "=") else {
        writeStandardError("Invalid asset spec \(spec). Expected name=file.\n")
        exit(2)
    }
    return Asset(
        name: String(spec[..<separator]),
        path: String(spec[spec.index(after: separator)...])
    )
}

func embeddedContent(path: String) throws -> String {
    var content = try String(contentsOfFile: path, encoding: .utf8)
    if content.hasSuffix("\n") {
        content.removeLast()
    }
    return content
}

func rawStringLiteral(_ content: String) -> String {
    var hashes = "#"
    while content.contains("\"\"\"\(hashes)") {
        hashes += "#"
    }
    return "\(hashes)\"\"\"\n\(content)\n\"\"\"\(hashes)"
}

var output = """
// This file is generated by InksteadWriterAssetsPlugin.
// Edit the source asset files under Sources/InksteadWriter instead.

enum GeneratedInksteadWriterAssets {
"""

for asset in assets {
    let content = try embeddedContent(path: asset.path)
    output += "\n    static let \(asset.name) = \(rawStringLiteral(content))\n"
}

let defaultTemplateComponents = assets.compactMap(componentAsset).sorted { $0.sourceName < $1.sourceName }
output += "\n    static let defaultTemplateComponents: [String: String] = ["
if defaultTemplateComponents.isEmpty {
    output += ":]"
} else {
    output += "\n"
    for component in defaultTemplateComponents {
        output += "        \(rawStringLiteral(component.sourceName)): \(component.constantName),\n"
    }
    output += "    ]"
}
output += "\n"

output += """

    static let defaultTemplateNames = ["layout", "home", "category", "post", "page", "404", "feed.xml", "feed.json"]

    static let defaultTemplates = [
        "layout": defaultThemeLayoutPlume,
        "home": defaultThemeHomePlume,
        "category": defaultThemeCategoryPlume,
        "post": defaultThemePostPlume,
        "page": defaultThemePagePlume,
        "404": defaultThemeNotFoundPlume,
        "feed.xml": defaultThemeFeedXMLPlume,
        "feed.json": defaultThemeFeedJSONPlume
    ]
}
"""

try FileManager.default.createDirectory(
    at: URL(fileURLWithPath: outputPath).deletingLastPathComponent(),
    withIntermediateDirectories: true
)
try output.write(toFile: outputPath, atomically: true, encoding: .utf8)

func componentAsset(_ asset: Asset) -> ComponentAsset? {
    let normalized = asset.path.replacingOccurrences(of: "\\", with: "/")
    if let name = sourceName(
        in: normalized,
        marker: "Sources/InksteadWriter/Templates/DefaultTheme/components/",
        prefix: "DefaultTemplates/components/"
    ) {
        return ComponentAsset(sourceName: name, constantName: asset.name)
    }
    return nil
}

func sourceName(in path: String, marker: String, prefix: String) -> String? {
    guard let range = path.range(of: marker) else {
        return nil
    }
    return prefix + path[range.upperBound...]
}
